{"name": "test_form_submission", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestFormValidation' object has no attribute 'driver'", "trace": "self = <test_form_validation.TestFormValidation object at 0x000002240277F890>\n\n    @pytest.mark.usefixtures(\"setup\")\n    def test_form_submission(self):\n>       self.driver.get(\"https://www.saucedemo.com/\")\nE       AttributeError: 'TestFormValidation' object has no attribute 'driver'\n\ntests\\test_form_validation.py:14: AttributeError"}, "start": 1725442283194, "stop": 1725442283194, "uuid": "74aa5760-9709-4147-8ad2-c03843e315f0", "historyId": "8b648fe9dc43d8ef412634672e6f4039", "testCaseId": "8b648fe9dc43d8ef412634672e6f4039", "fullName": "tests.test_form_validation.TestFormValidation#test_form_submission", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_form_validation"}, {"name": "subSuite", "value": "TestFormValidation"}, {"name": "host", "value": "MS"}, {"name": "thread", "value": "4288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_form_validation"}]}