{"name": "test_valid_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <test_login.TestLogin object at 0x0000022403075910>\n\n    @pytest.mark.usefixtures(\"setup\")\n    def test_valid_login(self):\n>       self.driver.get(\"https://www.saucedemo.com/\")\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\ntests\\test_login.py:15: AttributeError"}, "start": 1725442290991, "stop": 1725442290991, "uuid": "3d8a7bd7-8e13-4835-87d0-6ba13dc493e6", "historyId": "e7f254b9bfd5f2bc8d4a1ffa6dc7aebb", "testCaseId": "e7f254b9bfd5f2bc8d4a1ffa6dc7aebb", "fullName": "tests.test_login.TestLogin#test_valid_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS"}, {"name": "thread", "value": "4288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}